# Generated by Django 3.1.4 on 2020-12-20 13:18

from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gmail_id', models.EmailField(max_length=50)),
                ('bachelor_degree', models.CharField(choices=[('BCT', 'Bachelor in Computer Engineering'), ('BEX', 'Bachelor in Electronics Engineering'), ('BCE', 'Bachelor in Civil Engineering'), ('BME', 'Bachelor in Mechanical Engineering'), ('BArch', 'Bachelor in Architecture')], max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('rating', models.IntegerField(validators=[records.models.rating_validator])),
                ('year_passed', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020)),
                ('year_enrolled', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020)),
                ('scholarship', models.CharField(max_length=50)),
                ('job_at', models.CharField(choices=[('1', 'Google'), ('2', 'Apple')], max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('current_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_temporary', to='records.address')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_permanent', to='records.address')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.university')),
            ],
        ),
    ]
