# Generated by Django 3.1.4 on 2020-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='job',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
