# Generated by Django 3.1.4 on 2020-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20201221_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('NEP', 'NEPAL'), ('USA', 'United States of America')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='bachelor_degree',
            field=models.CharField(choices=[('', 'All'), ('BCT', 'Bachelor in Computer Engineering'), ('BEX', 'Bachelor in Electronics Engineering'), ('BCE', 'Bachelor in Civil Engineering'), ('BME', 'Bachelor in Mechanical Engineering'), ('BArch', 'Bachelor in Architecture')], max_length=50),
        ),
    ]
