# Generated by Django 3.1.4 on 2020-12-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20201223_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('', 'All'), ('NEP', 'Nepal'), ('USA', 'United States of America')], max_length=5),
        ),
    ]
